'''
Created on 13 Apr 2026

@author: Bharath.c
'''
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
options = webdriver.ChromeOptions()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
#
driver = webdriver.Chrome(options)
driver.implicitly_wait(10)
# 2
driver.get("https://testautomationpractice.blogspot.com/")
#3
current_page_title = driver.title
print("current_page_title:", current_page_title)
enter_name_name = driver.find_element(By.ID, 'name')
enter_name_name.send_keys("Bharath")
enter_name_email = driver.find_element(By.ID, 'email')
enter_name_email.send_keys("bharathgani31@gmail.com")
enter_name_phone = driver.find_element(By.ID, 'phone')
enter_name_phone.send_keys("8792477769")
enter_name_textarea = driver.find_element(By.ID, 'textarea')
enter_name_textarea.send_keys("# 123 india")
enter_name_field2 = driver.find_element(By.ID, 'field2')
enter_name_field2.send_keys("Hi")
enter_name_datepicker = driver.find_element(By.ID, 'datepicker')
enter_name_datepicker.send_keys("03/23/2026")
enter_name_wiki = driver.find_element(By.ID, 'Wikipedia1_wikipedia-search-input')
enter_name_wiki.send_keys("selenium")
wiki_search_icon = driver.find_element(By.CLASS_NAME, 'wikipedia-search-button')
wiki_search_icon.click()
enter_text_element1 = driver.find_element(By.LINK_TEXT, 'Selenium')
enter_text_element1.click()
wiki_name_radio = driver.find_element(By.ID, 'male')
wiki_name_radio.click()
wiki_week_check = driver.find_element(By.ID, 'thursday')
wiki_week_check.click()
wiki_week_check1 = driver.find_element(By.ID, 'monday')
wiki_week_check1.click()
wiki_week_check2 = driver.find_element(By.ID, 'tuesday')
wiki_week_check2.click()
wiki_week_check3 = driver.find_element(By.ID, 'wednesday')
wiki_week_check3.click()
wiki_week_check4 = driver.find_element(By.ID, 'friday')
wiki_week_check4.click()
wiki_week_check5 = driver.find_element(By.ID, 'saturday')
wiki_week_check5.click()
wiki_week_check6 = driver.find_element(By.ID, 'sunday')
wiki_week_check6.click()
enter_text_form = driver.find_element(By.ID, 'input1')
enter_text_form.send_keys("Hello")
enter_btn_clk = driver.find_element(By.ID, 'btn1')
enter_btn_clk.click()
enter_text_form1 = driver.find_element(By.ID, 'input2')
enter_text_form1.send_keys("My name is bharath")
enter_btn_clk1 = driver.find_element(By.ID, 'btn2')
enter_btn_clk1.click()
enter_text_form2 = driver.find_element(By.ID, 'input3')
enter_text_form2.send_keys("Bhuvan")
enter_btn_clk3 = driver.find_element(By.ID, 'btn3')
enter_btn_clk3.click()
enter_btn_lst = driver.find_element(By.ID, 'country')
enter_btn_lst.click()
enter_blg_element = driver.find_element(By.LINK_TEXT, 'Blog')
enter_blg_element.click()
enter_combx_list = driver.find_element(By.ID, 'comboBox')
enter_combx_list.click()
enter_btn_lst1 = driver.find_element(By.CLASS_NAME, 'form-control')
enter_btn_lst1.click()
enter_alt_button = driver.find_element(By.ID, 'alertBtn')
enter_alt_button.click()
enter_conf_button1 = driver.find_element(By.ID, 'confirmBtn')
enter_conf_button1.click()
enter_promt_button1 = driver.find_element(By.ID, 'promptBtn')
enter_promt_button1.click()
enter_pop_clk = driver.find_element(By.ID, 'PopUp')
enter_pop_clk.click()
enter_history_disp = driver.find_element(By.ID, 'toc-History')
enter_history_disp.click()
enter_color_test = driver.find_element(By.ID, 'post-body-1307673142697428135')
enter_color_test.click()
 #Action in the web element

