'''
Created on 27 Apr 2026

@author: Bharath.c
'''
from selenium import webdriver
from selenium.webdriver.common.by import By
options = webdriver.ChromeOptions()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")

driver = webdriver.Chrome(options)
driver.implicitly_wait(10)
driver.get("https://testautomationpractice.blogspot.com/")
# table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[1]/th[1]')
# print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[2]/td[1]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[3]/td[1]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[4]/td[1]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[5]/td[1]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[6]/td[1]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[7]/td[1]')
print(table_cell.text)
print("-------------------------auther----------------------------------")
#table_cell = driver.find_element(By.XPATH,'//*[@id="HTML1"]/div[1]/table/tbody/tr[1]/th[2]')
#print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[2]/td[2]')
print(table_cell.text) 
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[3]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[4]/td[2]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[5]/td[2]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[6]/td[2]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[7]/td[2]')
print(table_cell.text)
print("-------------------------subject--------------------------------")
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[1]/th[3]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[2]/td[3]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH,'//*[@id="HTML1"]/div[1]/table/tbody/tr[3]/td[3]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[4]/td[3]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[5]/td[3]')
print(table_cell.text)
table_cell= driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[6]/td[3]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[7]/td[3]')
print(table_cell.text)
print("----------------------------price------------------------------")
table_cell =driver.find_element(By.XPATH,'//*[@id="HTML1"]/div[1]/table/tbody/tr[1]/th[4]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[2]/td[4]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[3]/td[4]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[4]/td[4]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[5]/td[4]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[6]/td[4]')
print(table_cell.text)
table_cell = driver.find_element(By.XPATH,'//*[@id="HTML1"]/div[1]/table/tbody/tr[7]/td[4]')
print(table_cell.text)
print("--------------------------Task one completed---------------------")


rows = driver.find_element(By.XPATH, '//*[@id="HTML1"]/div[1]/table/tbody/tr[2]/td[1]')
for row in range(1,7):
    cols = driver.find_element(By.XPATH,'//*[@id="HTML1"]/div[1]/table/tbody/tr[2]/td[1]')
    for cols in range(0,4):
        print(cols.text,end = "")
    print()
    
    

